from google.colab import drive
drive.mount('/github')
%cd MyDrive/github
%ls -larh
# !git --version
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/.dotfiles.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/.files.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/AeenShop-Tool.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/AnjaniGourisaria.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/AnnesVille.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Anonymous.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Anti-bullying.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/App.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/APP___WEB_Pentest.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Arduino__BitLocker.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/awesome.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/awesome-hacking.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/awesome-pcaptools.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/awesome-pentest.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/awesome-termux-hacking.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Base.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Bettercap.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/bin2shell.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/binary_vulnerability.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/BlockChain.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/BlockChainChatting.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Boot-Adrino-Book.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/BootableUsB.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/BurpAcademy.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/BurpExtension-WhatsApp-Decryption-CheckPoint.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/BWAPP.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/byob.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/CASE01.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/case_app_reverse_eng.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/cobalt-strike-source-code-leak.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/codeigniter3.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/CodeIgniter_login.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/cool_python_apps.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/covid-vaccine-booking.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/CSSR.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/DELL.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Devesh-Project.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Django.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/dnmap.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Docker.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/ducky2arduino.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/DVWA.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/E-Commerce-Demo.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/eden.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Ephesus.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/esp8266_deauther.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/ESP8266_Deauth_All.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Exploit.Education_WriteUp.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/exploits.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Flutter-Pharmacy.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Flutter_Live_Location.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/fluxion.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Fuzzing.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/GDrive.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/gef.git
!git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/HackerPlatform.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Hacking.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/hackingtool.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/hacktricks.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Hande-Stealer.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/hello_world.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/html-poc.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Image_Steganography.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Important.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/IRIS.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/IsTheApp.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/JuiceShopGuide.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/KeepNotes.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/KitHack.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/LeeTechnologies.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Linux.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/linux-kernel.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/MacOS-in-windows-vm.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/mail.py.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Malware_Analysis.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Malware_Analysis_APK.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Malware_Code.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Malware_Collection.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/material-blog.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/medname.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/megabasterd.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/ML-From-Scratch.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/MobileApp-Pentest-Cheatsheet.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Notion_Notes.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/obfus.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Obfuscapk.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/OCRP6.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/openvpn-install.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/OSCP-Prep.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/PayloadsAllTheThings.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Pentest.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Pihole.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/pi_zero.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/poor-mans-pentest.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Port-Forwading.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Pradeep.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/pwncat.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/pwnedOrNot.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Python.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/python3TCP.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/RAASNet.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/RaidLabanCollege.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/reaver-wps-fork-t6x.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Rootkit_LKM.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/samytools.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Scripts.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/SecLists.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/sendwave.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/serenity.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/SMS_Server.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Social_Engineering.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/sql-injection-payload-list.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/static-binaries.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/strange.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Suraksha.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/SYNK.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/systemd-ngrok.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Teardroid-phprat.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/TheArtOfExploitation.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/TheArtOfExploitation2.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/theecommercespace.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/TheZooMalware.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/tmp.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/tollivertechnologies.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Tools.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/torshammer.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Tryhackme.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/use-spotify.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/VMWARE-unlocker.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Vpn__AnonSurf.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/We-pik.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Web.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Web_ReactJs.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/WiFiDuck.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/wifi_ducky.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Woking-Blockchain.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/Youtube.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/YoutubePvt.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/zexe.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/_Templates.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/internship-codigion.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/adison.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/backup-automatation-script.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/codigion.com.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/codigion.com-backup-fucked.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/ecommerce.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/interest-calculator.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/karate.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/meghalaya-olypmics.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/meghalayapost.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/patel.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/raidlabancollege.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/soweinternational.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/stardus.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/wepik-dev.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/zntraders.git
# !git clone https://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:x-oauth-basic@github.com/AnjaniGourisaria/BishalEnterprise.git




# !ssh-keygen -o
# %cat ~/.ssh/id_rsa.pub
